//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EZApartment.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApartmentEntities : DbContext
    {
        public ApartmentEntities()
            : base("name=ApartmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Apt_Task> Apt_Task { get; set; }
        public virtual DbSet<Apt_User> Apt_User { get; set; }
        public virtual DbSet<Apt_Work> Apt_Work { get; set; }
        public virtual DbSet<Work> Works { get; set; }
    }
}
